name: Run Unit Tests
on: [push, pull_request]
jobs:
  run-djwto-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Python Version ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
        env:
          TOX_SKIP_ENV: coverage

      - name: print
        run: echo " THE VALUE IS: ${{ matrix.python }}"

      - name: Build Coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.8' }}
        run: tox -e coverage

      - name: Upload coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.8' }}
        uses: codecov/codecov-action@v1
